### ISSUE TITLE
Dots from default reporter still show up

### ISSUE THREAD

**Issue by zemirco** [bcaudan/jasmine-spec-reporter#8]
Thanks for building the plugin!

In my tests the dots from the default reporter still show up. Take a look at them at Travis [nghellostyle#L742](https://travis-ci.org/zemirco/nghellostyle#L742). They break the indentation for list items.

Here is my [config](https://github.com/zemirco/nghellostyle/blob/master/test/e2e/protractor.conf.js#L18). Is it something on my side or is it a bug?

**Comment by bcherny** [comment]
can you add this section back? https://github.com/bcaudan/jasmine-spec-reporter/tree/v2.0.0#remove-protractor-dot-reporter

still an issue with jasmine-spec-reporter@2.4.0 + jasmine-core@2.3.4 + protractor@2.2.0

**Comment by bcaudan** [comment]
This section has been moved to [configuration](https://github.com/bcaudan/jasmine-spec-reporter#configuration) > [protractor](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/protractor-configuration.md)

**Comment by ahmed-abdulmoniem** [comment]
Still not working for me even if I applied the workaround

```
exports.config = {
    seleniumServerJar: 'node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar',
    specs: ['tests/e2e/*.js'],
    multiCapabilities: [{
        browserName: 'chrome'
    }],
    jasmineNodeOpts:{
        print: function () {}
    },
    onPrepare: function () {
        var SpecReporter = require('jasmine-spec-reporter');
        // add jasmine spec reporter
        jasmine.getEnv().addReporter(new SpecReporter({
            displayStacktrace: 'all',      // display stacktrace for each failed assertion, values: (all|specs|summary|none)
            displaySuccessesSummary: true, // display summary of all successes after execution
            displayFailuresSummary: true,   // display summary of all failures after execution
            displayPendingSummary: true,    // display summary of all pending specs after execution
            displaySuccessfulSpec: true,    // display each successful spec
            displayFailedSpec: true,        // display each failed spec
            displayPendingSpec: true,      // display each pending spec
            displaySpecDuration: true,     // display each spec duration
            displaySuiteNumber: true,      // display each suite number (hierarchical)
            colors: {
                success: 'green',
                failure: 'red',
                pending: 'yellow'
            },
            prefixes: {
                success: '✓ ',
                failure: '✗ ',
                pending: '* '
            },
            customProcessors: []
        }));
    }
};
```

**Comment by disjunction** [comment]
@ahmed-abdulmoniem if you upgrade to jasmine 2.5.2, then you can use `clearReporters()` instead of the ugly workaround. Here's how i fixed it in my case: disjunction/jasme@8a06ee4

**Comment by ahmed-abdulmoniem** [comment]
@disjunction It can't be set in conf file? I should call it manually?

**Comment by disjunction** [comment]
@ahmed-abdulmoniem I saw a pull request about adding it to the options, but can't find it now. Anyway as far as I can see it not in the current code.

**Comment by valterkraemer** [comment]
This worked for me:
```
onPrepare: function() {
  var env = jasmine.getEnv();

  env.clearReporters();

  var SpecReporter = require('jasmine-spec-reporter');

  env.addReporter(new SpecReporter({
    displayStacktrace: true
  }));
}
```

**Comment by ahmed-abdulmoniem** [comment]
@valterkraemer This worked for me. Thanks.

**Comment by mrowles** [comment]
`env.clearReporters is not a function` for me!

**Comment by bcaudan** [comment]
You need [jasmine@2.5.2](https://github.com/jasmine/jasmine/blob/master/release_notes/2.5.2.md) to use `env.clearReporters`

**Comment by jeremyhewett** [comment]
`env.clearReporters` breaks the exit code of the process because it removes the Jasmine `CompletionReporter` which handles this. Your process will now always exit with code `0` even when some tests fail.

**Comment by disjunction** [comment]
@jeremyhewett I've just tested, and the exit code did work for me. Tested with jasmine@2.5.3

**Comment by xkamil** [comment]
Hi. Here is my sloution: 

`jasmineNodeOpts: {
        defaultTimeoutInterval: 30000,
        // overriding print() function disables dot reporter
        print: function () {
        }
    },

    onPrepare: function () {
        browser.manage().timeouts().implicitlyWait(1000);
        
        //adding spec reporter
        let SpecReporter = require('jasmine-spec-reporter').SpecReporter;
        jasmine.getEnv().addReporter(new SpecReporter({
            spec: {
                displayStacktrace: false
            }
        }));
    }`

**Comment by bcaudan** [comment]
Seems pretty close to https://github.com/bcaudan/jasmine-spec-reporter/blob/master/examples/protractor/README.md

**Comment by demisx** [comment]
The @xkamil suggestion doesn't seem to work in jasmine 3.4.0. :(

**Comment by bcaudan** [comment]
@demisx I've just tested it with the [protractor example of this repository](https://github.com/bcaudan/jasmine-spec-reporter/tree/master/examples/protractor) with:
- jasmine@3.4.0
- jasmine-core@3.4.0 
- protractor@5.4.2

and it works fine on my machine.
Can you try to run this example? 
If it is still not working, please open a new issue.

**Comment by bcaudan** [comment]
The initial issue has been resolved by the hack described in the documentation. I'm locking the conversation to avoid spam in this old issue.
Feel free to open a new issue in case of regression.
