### ISSUE TITLE
Chrome version compatible with jasmine-spec-reporter

### ISSUE THREAD

**Issue by hassankaz** [bcaudan/jasmine-spec-reporter#687]
Hello,

I started getting the following error when running protractor test after upgrading chromedriver version to 79;

Failed: SpecReporter.sendHistoryArrayToSpecReporter is not a function

I haven't changed anything else in config file so I suspect this is a versioning issue.
Could anyone please advice me which version of chromedriver is compatible with jasmine-spect-reporter 4.2.1?

Thank you so much in advance
Kazue
